### ISSUE TITLE
not tracking cohort biomass correctly

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Library-Universal-Cohort#1]
I think there's a problem with the Universal Cohort Library.

I noticed that my biomass (AGB) in my DGS-short and DGS-succession csv files changed A LOT between time step 0 and time step 1 when I ran a test landscape (like 15,000 g/m2 difference!). It was fine in a single-cell.

So… I ran the test landscape for NECN (Core8-NECN8-Landscape) and noticed that NECN has the same problem. Time step 0 is 18,000 and time step 1 is 8,700. That’s a big change when ANPP is only 139.

I’m worried something is not working correctly with the universal cohort library with a landscape with multiple cells. When you add up the changes (deltawood and deltaleaf) from the ComputeChange method, they don’t add up to the biomass at the end of the year (at least for year 1). Some of the species seem fine, while others have huge jumps in biomass between 1y timesteps.

**Comment by rmscheller** [comment]
Austen,
I'm sorry I can't help out this week or next; I'm fully booked.
Here are a few thoughts:
* Is the problem with universal attributes or ExandoObjects?  I suggest running Biomass Succession at an annual time step to see if you see the same error.  If not, then the universal attributes are OK.
* Is there memory leakage?  I suggest next try running NECN single-cell with and without multiple cohorts.  If the error only happens with multiple cohorts, it could be a memory leakage problem (ugh).  On the other hand, it could be an order of operations problem.  It is odd that the error only happens in year 1, suggesting not a memory leakage problem, which would grow worse over time.
* The oddest thing is that AGB declines at year 1 and then immediately bounces back year 2.  The bounce back exceeds ANPP (the delta).  Note that NECN initializes with ANPP = 0:  https://github.com/LANDIS-II-Foundation/Extension-NECN-Succession/blob/master/src/InitialBiomass.cs#L93  That might create the initial drop, but why then the rapid recovery in AGB?

Thanks for your help!

**Comment by rmscheller** [comment]
p.s. If ANPP = 0 is indeed causing the problem, a good proxy is (leaf-Biomass / leaf-longevity).

**Comment by rmscheller** [comment]
It appears that we should definitely be returning only the delta, see:  https://github.com/LANDIS-II-Foundation/Library-Universal-Cohort/blob/main/Cohort.cs#L183

I ran Biomass Succession at a 1-year time step, and didn't spot any immediate problems with AGB dynamics.  Biomass Succession correctly returns the delta (not biomass + delta).

What is weird is that I tested NECN with CohortBiomass.ComputeChange both returning (biomass + delta) and returning (delta) and got nearly the same result!  (This was single cell, two cohorts.) Returning (delta) did cause more initial decline than returning (biomass+delta) but it was a very marginal difference.  I would expect that the AGB would be increasing exponentially when returning (biomass+delta).   More investigations forthcoming.

**Comment by rmscheller** [comment]
Another interesting note:  I was wondering if we're properly logging some of these data and we were not.

https://github.com/LANDIS-II-Foundation/Extension-NECN-Succession/blob/master/src/Main.cs#L227

I changed this to "total += cohort.Data.Biomass;" and now the version of ComputeChange that returns (delta) has a very flat trajectory with almost no initial dip.  

I also notice that the NECN calibrate log file doesn't report out cohort.Data.Biomass or cohort.Data.ANPP, making it hard to track.  I'll work on that next.

**Comment by rmscheller** [comment]
OK, maybe this is the problem:  cohort.Data.ANPP is not being recorded correctly.  Although the interface was updated, the values are not being recorded.

https://github.com/LANDIS-II-Foundation/Library-Universal-Cohort/blob/main/ICalculator.cs#L36

**Comment by rmscheller** [comment]
I had one important insight while taking a bath...  Perhaps ANPP is very small because leafBiomass is very small (via the LAI limitation).  So, why would leafBiomass be very small?

https://github.com/LANDIS-II-Foundation/Extension-NECN-Succession/blob/master/src/CohortBiomass.cs#L176

This should be:  tempObject.WoodBiomass += deltaWood;  tempObject.LeafBiomass += deltaLeaf;
because the AdditionalParameters (otherParams) are being REPLACED, not modified.

I haven't had time to test this yet.

**Comment by rmscheller** [comment]
Also, 

https://github.com/LANDIS-II-Foundation/Extension-NECN-Succession/blob/master/src/CohortBiomass.cs#L47

Should be:

tempObject.WoodBiomass = cohort.Data.AdditionalParameters.WoodBiomass;
tempObject.LeafBiomass = cohort.Data.AdditionalParameters.LeafBiomass;

**Comment by mslucash** [comment]
I think this issue could be marked as resolved now.
